wandb_version: 1

batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 100
image_size:
  desc: null
  value: 640
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710663136.0
    t:
      1:
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.4
      8:
      - 1
      - 5
      13: linux-x86_64
    framework: torch
